### ISSUE TITLE
removing symlinks

### ISSUE THREAD

**Issue by ckressibucher** [sitewards/modman-php#17]
Is there a reason that symlink-directories are not removed by unlink in `Modman_Resource_Remover::doRemoveResource`?

Currently the following code

```
		if (is_dir($sElementPath)){
			if (is_link($sElementPath) OR $this->isFolderEmpty($sElementPath)){
				rmdir($sElementPath);
			}
                 }
```

does not remove my module completely (seems rmdir does not work on symlinks that point to a non-empty directory).

Suggestion:

```
      if (is_dir($sElementPath)){
            if (is_link($sElementPath)) {
                unlink($sElementPath);
            } elseif ($this->isFolderEmpty($sElementPath)){
	        rmdir($sElementPath);
             }
      }
```

.. but I'm not sure if that would break some other functionality...

**Comment by mryvlin** [comment]
fixed in pull request #38
