### ISSUE TITLE
.basedir check in getAllModules

### ISSUE THREAD

**Issue by mvenghaus** [sitewards/modman-php#23]
In your getAllModules method you try to remove the .basedir file. 

$iBaseDir = array_search(Modman_Command_Init::getBaseDirFile(), $aDirEntries);

Modman_Command_Init::getBaseDirFile() returns ".modman/.basedir" .. but $aDirEntries only contains ".basedir".

It only works when I  change this line to

$iBaseDir = array_search(Modman_Command_Init::MODMAN_BASEDIR_FILE, $aDirEntries);

Is it a bug or do I something wrong?

**Comment by dmanners** [comment]
This could easily be a bug. We will investigate this and see if we can find the perfect solution.
