### ISSUE TITLE
@import duplicate basedir added

### ISSUE THREAD

**Issue by mvenghaus** [sitewards/modman-php#24]
I've a modman file with this content:

@import Project_Base

The function "doImport" uses the same method as "doDeploy" "$sSymlink = $oLine->getSymlink();" .. in this method the basedir is added. So both "doImport" and "doDeploy" add the basedir.

When i force the doImport not to add the basedir everything is working as it should.

Bug or wrong configuration?

**Comment by dmanners** [comment]
Do you have a example of this so we can easily reproduce it?
