### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by barbazul** [sitewards/modman-php#47]
No commits in 18 months.

Unmerged 2 years old PRs.

Should someone pick up the mantle to keep it alive?

**Comment by aboritskiy** [comment]
actually yes, we don't use that modman on windows as extensive as we used to. Reason for that - we switched to composer and linux VMs. Therefore this project became effectively abandoned, though we have never officially given up on it.

**Comment by aboritskiy** [comment]
@barbazul does that answer your question?

**Comment by barbazul** [comment]
It does. 😥

I am very likely to pick this up myself or build an alternative in the near
future (if no one else does) as we are still using this very heavily.
